server:
  port: 8090
spring:
  application:
    name: whr-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whr?serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      filters: stat
      aop-patterns:
        - com.at.wangshixiu.whr
      stat-view-servlet:
        enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.css,*.gif,*.jpg,*.png,*.ico,/druid/*,/doc.html"
  redis:
    port: 6379
    database: 3
    host: localhost
    jedis:
      pool:
        max-active: 5

mybatis-plus:
#  id类型
  global-config:
    db-config:
      id-type: ASSIGN_ID
#      打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

sa-token:
  #token的前缀
  token-prefix: whr
  # token名称 (同时也是cookie名称)
  token-name: defalut-token
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 7200
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
